version: '3.8'
services:
  redis:
    image: redis:7
    container_name: feedbacker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server 
      --save 60 1 
      --appendonly yes

volumes:
  redis_data:
    driver: local
