spring:
  application:
    name: Feedbacker

  datasource:
    url: jdbc:mysql://13.210.204.61:3306/feedbacker?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
      host: smtp.qq.com
      port: 587
      username: 490377187@qq.com
      password: khhocvtqosxycafd
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.ssl.trust: smtp.qq.com
  redis:
    host: 13.210.204.61
    port: 6379
    timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.feedbacker.entity

jwt:
  secret: rKkSUrPTdlc4/d7CLwb1Xg2GipF5BqnF7VGCBDiNDjI=
  expiration-ms: 86400000